en-US = [
  "Gamescope", "MangoHud", "Solaris", "Zhuyin", "NVENC", "Quantizer",
  "Deblocking", "Subpixel", "Filesystem", "Btrfs",
  "keyring", "zpool", "vdev", "xattrs", "dnodes", "quantizer",
  "quantizers", "bitrate", "bitrates", "filesystem",
  "systemd-nspawn", # Commands
  "subinterval", "subintervals", "antiderivatives", "integrand",
  "speakwritten", "Ingsoc" # "1984"
]
